version: '2'
services:
  ubuntu_mini:
    #build: ./
    image: brunobcf/vrtp2
    #restart: always
    container_name: ubuntu_mininet
    volumes:
      - ubuntu_vol:/home/ubuntu
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
    ports:
      - 6653:6653
      - 6633:6633
    networks:
      - network1 
    privileged: true
    environment:
     - DISPLAY
    #Testa correr programa gráfico do container. Se o X server do host usar OpenGL, os drivers da placa de video tem que ser instaladas também no container
    #command: bash -c "service openvswitch-switch start && xmessage Container iniciado"
    #command: bash -c "service openvswitch-switch start && wireshark"
    command: bash -c "service openvswitch-switch start && tail -F /dev/null"
    #O comando tail -F /dev/null serve apenas para fazer com que o container não termine após a execução do service start

volumes:
  ubuntu_vol:
    driver_opts:
      type: none
      device: $PWD
      o: bind

networks:
  network1:
    driver: bridge
