version: '2'
services:
  ubuntu_mini:
    build: ./
    restart: always
    container_name: ubuntu_mininet
    volumes:
      - ubuntu_vol:/home/ubuntu
    ports:
      - 6653:6653
      - 6633:6633

volumes:
  ubuntu_vol:
    driver_opts:
      type: none
      device: $HOME/
      o: bind
